# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  panda_joint1: 0.0
  panda_joint2: -0.785
  panda_joint3: 0.0
  panda_joint4: -2.356
  panda_joint5: 0.0
  panda_joint6: 1.571
  panda_joint7: 0.785

# initial_positions:
#   panda_joint1: 0.785
#   panda_joint2: 0.0
#   panda_joint3: 0.0
#   panda_joint4: 0.0
#   panda_joint5: 0.0
#   panda_joint6: 1.571
#   panda_joint7: 0.785
#   panda_finger_joint1: 0.04

# 90 = 1.571
# 180 = 3.142
# 30 = 0.5235987756
# 120 = 2.094395102
# 135 = 2.356
# 145 = 2.5307
# 45 = 0.785