# Default initial positions for pr2's ros2_control fake system

initial_positions:
  l_elbow_flex_joint: 0
  l_forearm_roll_joint: 0
  l_gripper_joint: 0
  l_gripper_l_finger_joint: 0
  l_gripper_motor_screw_joint: 0
  l_gripper_motor_slider_joint: 0
  l_shoulder_lift_joint: 0
  l_shoulder_pan_joint: 0
  l_upper_arm_roll_joint: 0
  l_wrist_flex_joint: 0
  l_wrist_roll_joint: 0
  r_elbow_flex_joint: 0
  r_forearm_roll_joint: 0
  r_gripper_joint: 0
  r_gripper_l_finger_joint: 0
  r_gripper_motor_screw_joint: 0
  r_gripper_motor_slider_joint: 0
  r_shoulder_lift_joint: 0
  r_shoulder_pan_joint: 0
  r_upper_arm_roll_joint: 0
  r_wrist_flex_joint: 0
  r_wrist_roll_joint: 0