# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: GripperCommand
    joints:
      - l_gripper_l_finger_joint
      - l_gripper_motor_slider_joint
      - l_gripper_motor_screw_joint
      - l_gripper_joint
    action_ns: gripper_cmd
    default: true
  right_hand_controller:
    type: GripperCommand
    joints:
      - r_gripper_l_finger_joint
      - r_gripper_motor_slider_joint
      - r_gripper_motor_screw_joint
      - r_gripper_joint
    action_ns: gripper_cmd
    default: true